#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
	if [ "$1" = "remove" ]; then
		systemctl disable --now virgild.service >/dev/null 2>&1 || true
	else
		systemctl stop virgild.service >/dev/null 2>&1 || true
	fi
fi
exit 0
